country_to_continent = {
    'Afghanistan': 'Asia',
    'Albania': 'Europe',
    'Algeria': 'Africa',
    'Andorra': 'Europe',
    'Angola': 'Africa',
    'Antigua and Barbuda': 'North America',
    'Argentina': 'South America',
    'Armenia': 'Asia',
    'Australia': 'Oceania',
    'Austria': 'Europe',
    'Azerbaijan': 'Asia',
    'Bahamas': 'North America',
    'Bahrain': 'Asia',
    'Bangladesh': 'Asia',
    'Barbados': 'North America',
    'Belarus': 'Europe',
    'Belgium': 'Europe',
    'Belize': 'North America',
    'Benin': 'Africa',
    'Bhutan': 'Asia',
    'Bolivia': 'South America',
    'Bosnia and Herzegovina': 'Europe',
    'Botswana': 'Africa',
    'Brazil': 'South America',
    'Brunei': 'Asia',
    'Bulgaria': 'Europe',
    'Burkina Faso': 'Africa',
    'Burundi': 'Africa',
    'Cabo Verde': 'Africa',
    'Cambodia': 'Asia',
    'Cameroon': 'Africa',
    'Canada': 'North America',
    'Central African Republic': 'Africa',
    'Chad': 'Africa',
    'Chile': 'South America',
    'China': 'Asia',
    'Colombia': 'South America',
    'Comoros': 'Africa',
    'Congo (Congo-Brazzaville)': 'Africa',
    'Costa Rica': 'North America',
    'Croatia': 'Europe',
    'Cuba': 'North America',
    'Cyprus': 'Asia',
    'Czechia (Czech Republic)': 'Europe',
    'Democratic Republic of the Congo': 'Africa',
    'Denmark': 'Europe',
    'Djibouti': 'Africa',
    'Dominica': 'North America',
    'Dominican Republic': 'North America',
    'Ecuador': 'South America',
    'Egypt': 'Africa',
    'El Salvador': 'North America',
    'Equatorial Guinea': 'Africa',
    'Eritrea': 'Africa',
    'Estonia': 'Europe',
    'Eswatini (fmr. "Swaziland")': 'Africa',
    'Ethiopia': 'Africa',
    'Fiji': 'Oceania',
    'Finland': 'Europe',
    'France': 'Europe',
    'Gabon': 'Africa',
    'Gambia': 'Africa',
    'Georgia': 'Asia',
    'Germany': 'Europe',
    'Ghana': 'Africa',
    'Greece': 'Europe',
    'Grenada': 'North America',
    'Guatemala': 'North America',
    'Guinea': 'Africa',
    'Guinea-Bissau': 'Africa',
    'Guyana': 'South America',
    'Haiti': 'North America',
    'Honduras': 'North America',
    'Hungary': 'Europe',
    'Iceland': 'Europe',
    'India': 'Asia',
    'Indonesia': 'Asia',
    'Iran': 'Asia',
    'Iraq': 'Asia',
    'Ireland': 'Europe',
    'Israel': 'Asia',
    'Italy': 'Europe',
    'Jamaica': 'North America',
    'Japan': 'Asia',
    'Jordan': 'Asia',
    'Kazakhstan': 'Asia',
    'Kenya': 'Africa',
    'Kiribati': 'Oceania',
    'Kuwait': 'Asia',
    'Kyrgyzstan': 'Asia',
    'Laos': 'Asia',
    'Latvia': 'Europe',
    'Lebanon': 'Asia',
    'Lesotho': 'Africa',
    'Liberia': 'Africa',
    'Libya': 'Africa',
    'Liechtenstein': 'Europe',
    'Lithuania': 'Europe',
    'Luxembourg': 'Europe',
    'Madagascar': 'Africa',
    'Malawi': 'Africa',
    'Malaysia': 'Asia',
    'Maldives': 'Asia',
    'Mali': 'Africa',
    'Malta': 'Europe',
    'Marshall Islands': 'Oceania',
    'Mauritania': 'Africa',
    'Mauritius': 'Africa',
    'Mexico': 'North America',
    'Micronesia': 'Oceania',
    'Moldova': 'Europe',
    'Monaco': 'Europe',
    'Mongolia': 'Asia',
    'Montenegro': 'Europe',
    'Morocco': 'Africa',
    'Mozambique': 'Africa',
    'Myanmar (Burma)': 'Asia',
    'Namibia': 'Africa',
    'Nauru': 'Oceania',
    'Nepal': 'Asia',
    'Netherlands': 'Europe',
    'New Zealand': 'Oceania',
    'Nicaragua': 'North America',
    'Niger': 'Africa',
    'Nigeria': 'Africa',
    'North Korea': 'Asia',
    'North Macedonia': 'Europe',
    'Norway': 'Europe',
    'Oman': 'Asia',
    'Pakistan': 'Asia',
    'Palau': 'Oceania',
    'Palestine State': 'Asia',
    'Panama': 'North America',
    'Papua New Guinea': 'Oceania',
    'Paraguay': 'South America',
    'Peru': 'South America',
    'Philippines': 'Asia',
    'Poland': 'Europe',
    'Portugal': 'Europe',
    'Qatar': 'Asia',
    'Romania': 'Europe',
    'Russia': 'Europe',
    'Rwanda': 'Africa',
    'Saint Kitts and Nevis': 'North America',
    'Saint Lucia': 'North America',
    'Saint Vincent and the Grenadines': 'North America',
    'Samoa': 'Oceania',
    'San Marino': 'Europe',
    'Sao Tome and Principe': 'Africa',
    'Saudi Arabia': 'Asia',
    'Senegal': 'Africa',
    'Serbia': 'Europe',
    'Seychelles': 'Africa',
    'Sierra Leone': 'Africa',
    'Singapore': 'Asia',
    'Slovakia': 'Europe',
    'Slovenia': 'Europe',
    'Solomon Islands': 'Oceania',
    'Somalia': 'Africa',
    'South Africa': 'Africa',
    'South Korea': 'Asia',
    'South Sudan': 'Africa',
    'Spain': 'Europe',
    'Sri Lanka': 'Asia',
    'Sudan': 'Africa',
    'Suriname': 'South America',
    'Sweden': 'Europe',
    'Switzerland': 'Europe',
    'Syria': 'Asia',
    'Tajikistan': 'Asia',
    'Tanzania': 'Africa',
    'Thailand': 'Asia',
    'Timor-Leste': 'Asia',
    'Togo': 'Africa',
    'Tonga': 'Oceania',
    'Trinidad and Tobago': 'North America',
    'Tunisia': 'Africa',
    'Turkey': 'Asia',
    'Turkmenistan': 'Asia',
    'Tuvalu': 'Oceania',
    'Uganda': 'Africa',
    'Ukraine': 'Europe',
    'United Arab Emirates': 'Asia',
    'United Kingdom': 'Europe',
    'United States': 'North America',
    'USA': 'North America',
    'UK': 'Europe',
    'Uruguay': 'South America',
    'Uzbekistan': 'Asia',
    'Vanuatu': 'Oceania',
    'Vatican City': 'Europe',
    'Venezuela': 'South America',
    'Vietnam': 'Asia',
    'Yemen': 'Asia',
    'Zambia': 'Africa',
    'Zimbabwe': 'Africa'
}

country_to_code =  {
    'United States': 'USA',
    'China': 'CHN',
    'Germany': 'DEU',
    'Italy': 'ITA',
    'United Kingdom': 'GBR',
    'France': 'FRA',
    'India': 'IND',
    'Japan': 'JPN',
    'South Korea': 'KOR',
    'Canada': 'CAN',
    'Switzerland': 'CHE',
    'Poland': 'POL',
    'Australia': 'AUS',
    'Belgium': 'BEL',
    'Netherlands': 'NLD',
    'Spain': 'ESP',
    'Denmark': 'DNK',
    'Sweden': 'SWE',
    'Egypt': 'EGY',
    'New Zealand': 'NZL',
    'Lithuania': 'LTU',
    'Israel': 'ISR',
    'Austria': 'AUT',
    'South Africa': 'ZAF',
    'Pakistan': 'PAK',
    'Singapore': 'SGP',
    'Slovenia': 'SVN',
    'Greece': 'GRC',
    'Finland': 'FIN',
    'Russia': 'RUS',
    'Brazil': 'BRA',
    'Iran': 'IRN',
    'Saudi Arabia': 'SAU',
    'Portugal': 'PRT',
    'Malaysia': 'MYS',
    'Thailand': 'THA',
    'Norway': 'NOR',
    'Hungary': 'HUN',
    'Bangladesh': 'BGD',
    'Mexico': 'MEX',
    'Argentina': 'ARG',
    'Jordan': 'JOR',
    'United Arab Emirates': 'ARE',
    'Slovakia': 'SVK',
    'Ireland': 'IRL',
    'Romania': 'ROU',
    'Chile': 'CHL',
    'Serbia': 'SRB',
    'Philippines': 'PHL',
    'Estonia': 'EST',
    'Ukraine': 'UKR',
    'Monaco': 'MCO',
    'Colombia': 'COL',
    'Croatia': 'HRV',
    'Morocco': 'MAR',
    'Tunisia': 'TUN',
    'Indonesia': 'IDN',
    'Latvia': 'LVA',
    'Vietnam': 'VNM',
    'Ecuador': 'ECU',
    'Bulgaria': 'BGR',
    'Zambia': 'ZMB',
    'Venezuela': 'VEN',
    'Lebanon': 'LBN',
    'Rwanda': 'RWA',
    'Oman': 'OMN',
    'Luxembourg': 'LUX',
    'Cyprus': 'CYP',
    'Uruguay': 'URY',
    'Botswana': 'BWA',
    'Algeria': 'DZA',
    'Grenada': 'GRD',
    'Jamaica': 'JAM',
    'Kuwait': 'KWT',
    'Sudan': 'SDN',
    'Peru': 'PER',
    'Qatar': 'QAT',
    'Zimbabwe': 'ZWE',
    'Bosnia and Herzegovina': 'BIH',
    'Sri Lanka': 'LKA',
    'Nepal': 'NPL',
    'Armenia': 'ARM',
    'Kenya': 'KEN',
    'Cuba': 'CUB',
    'Ethiopia': 'ETH',
    'Nigeria': 'NGA'
}

code_to_region_WHO ={
 'ABW': 'AMR',
 'AFG': 'EMR',
 'AGO': 'AFR',
 'AIA': 'AMR',
 'ALB': 'EUR',
 'AND': 'EUR',
 'ARE': 'EMR',
 'ARG': 'AMR',
 'ARM': 'EUR',
 'ASM': 'WPR',
 'ATG': 'AMR',
 'AUS': 'WPR',
 'AUT': 'EUR',
 'AZE': 'EUR',
 'BDI': 'AFR',
 'BEL': 'EUR',
 'BEN': 'AFR',
 'BES': 'AMR',
 'BFA': 'AFR',
 'BGD': 'SEAR',
 'BGR': 'EUR',
 'BHR': 'EMR',
 'BHS': 'AMR',
 'BIH': 'EUR',
 'BLR': 'EUR',
 'BLZ': 'AMR',
 'BMU': 'AMR',
 'BOL': 'AMR',
 'BRA': 'AMR',
 'BRB': 'AMR',
 'BRN': 'WPR',
 'BTN': 'SEAR',
 'BWA': 'AFR',
 'CAF': 'AFR',
 'CAN': 'AMR',
 'CHE': 'EUR',
 'CHL': 'AMR',
 'CHN': 'WPR',
 'CIV': 'AFR',
 'CMR': 'AFR',
 'COD': 'AFR',
 'COG': 'AFR',
 'COK': 'WPR',
 'COL': 'AMR',
 'COM': 'AFR',
 'CPV': 'AFR',
 'CRI': 'AMR',
 'CUB': 'AMR',
 'CUW': 'AMR',
 'CYM': 'AMR',
 'CYP': 'EUR',
 'CZE': 'EUR',
 'DEU': 'EUR',
 'DJI': 'EMR',
 'DMA': 'AMR',
 'DNK': 'EUR',
 'DOM': 'AMR',
 'DZA': 'AFR',
 'ECU': 'AMR',
 'EGY': 'EMR',
 'ERI': 'AFR',
 'ESP': 'EUR',
 'EST': 'EUR',
 'ETH': 'AFR',
 'FIN': 'EUR',
 'FJI': 'WPR',
 'FLK': 'AMR',
 'FRA': 'EUR',
 'FRO': 'EUR',
 'FSM': 'WPR',
 'GAB': 'AFR',
 'GBR': 'EUR',
 'GEO': 'EUR',
 'GHA': 'AFR',
 'GIB': 'EUR',
 'GIN': 'AFR',
 'GLP': 'AMR',
 'GMB': 'AFR',
 'GNB': 'AFR',
 'GNQ': 'AFR',
 'GRC': 'EUR',
 'GRD': 'AMR',
 'GRL': 'EUR',
 'GTM': 'AMR',
 'GUF': 'AMR',
 'GUM': 'WPR',
 'GUY': 'AMR',
 'HND': 'AMR',
 'HRV': 'EUR',
 'HTI': 'AMR',
 'HUN': 'EUR',
 'IDN': 'SEAR',
 'IMN': 'EUR',
 'IND': 'SEAR',
 'IRL': 'EUR',
 'IRN': 'EMR',
 'IRQ': 'EMR',
 'ISL': 'EUR',
 'ISR': 'EUR',
 'ITA': 'EUR',
 'JAM': 'AMR',
 'JOR': 'EMR',
 'JPN': 'WPR',
 'KAZ': 'EUR',
 'KEN': 'AFR',
 'KGZ': 'EUR',
 'KHM': 'WPR',
 'KIR': 'WPR',
 'KNA': 'AMR',
 'KOR': 'WPR',
 'KWT': 'EMR',
 'LAO': 'WPR',
 'LBN': 'EMR',
 'LBR': 'AFR',
 'LBY': 'EMR',
 'LCA': 'AMR',
 'LIE': 'EUR',
 'LKA': 'SEAR',
 'LSO': 'AFR',
 'LTU': 'EUR',
 'LUX': 'EUR',
 'LVA': 'EUR',
 'MAR': 'EMR',
 'MCO': 'EUR',
 'MDA': 'EUR',
 'MDG': 'AFR',
 'MDV': 'SEAR',
 'MEX': 'AMR',
 'MHL': 'WPR',
 'MKD': 'EUR',
 'MLI': 'AFR',
 'MLT': 'EUR',
 'MMR': 'SEAR',
 'MNE': 'EUR',
 'MNG': 'WPR',
 'MNP': 'WPR',
 'MOZ': 'AFR',
 'MRT': 'AFR',
 'MSR': 'AMR',
 'MTQ': 'AMR',
 'MUS': 'AFR',
 'MWI': 'AFR',
 'MYS': 'WPR',
 'MYT': 'AFR',
 'NAM': 'AFR',
 'NCL': 'WPR',
 'NER': 'AFR',
 'NGA': 'AFR',
 'NIC': 'AMR',
 'NIU': 'WPR',
 'NLD': 'EUR',
 'NOR': 'EUR',
 'NPL': 'SEAR',
 'NRU': 'WPR',
 'NZL': 'WPR',
 'OMN': 'EMR',
 'PAK': 'EMR',
 'PAN': 'AMR',
 'PER': 'AMR',
 'PHL': 'WPR',
 'PLW': 'WPR',
 'PNG': 'WPR',
 'POL': 'EUR',
 'PRI': 'AMR',
 'PRK': 'SEAR',
 'PRT': 'EUR',
 'PRY': 'AMR',
 'PSE': 'EMR',
 'PYF': 'WPR',
 'QAT': 'EMR',
 'REU': 'AFR',
 'ROU': 'EUR',
 'RUS': 'EUR',
 'RWA': 'AFR',
 'SAU': 'EMR',
 'SDN': 'EMR',
 'SDN736': 'EMR',
 'SEN': 'AFR',
 'SGP': 'WPR',
 'SHN': 'AFR',
 'SLB': 'WPR',
 'SLE': 'AFR',
 'SLV': 'AMR',
 'SMR': 'EUR',
 'SOM': 'EMR',
 'SPM': 'AMR',
 'SRB': 'EUR',
 'SSD': 'AFR',
 'STP': 'AFR',
 'SUR': 'AMR',
 'SVK': 'EUR',
 'SVN': 'EUR',
 'SWE': 'EUR',
 'SWZ': 'AFR',
 'SXM': 'AMR',
 'SYC': 'AFR',
 'SYR': 'EMR',
 'TCA': 'AMR',
 'TCD': 'AFR',
 'TGO': 'AFR',
 'THA': 'SEAR',
 'TJK': 'EUR',
 'TKL': 'WPR',
 'TKM': 'EUR',
 'TLS': 'SEAR',
 'TON': 'WPR',
 'TTO': 'AMR',
 'TUN': 'EMR',
 'TUR': 'EUR',
 'TUV': 'WPR',
 'TZA': 'AFR',
 'UGA': 'AFR',
 'UKR': 'EUR',
 'URY': 'AMR',
 'USA': 'AMR',
 'UZB': 'EUR',
 'VCT': 'AMR',
 'VEN': 'AMR',
 'VGB': 'AMR',
 'VIR': 'AMR',
 'VNM': 'WPR',
 'VUT': 'WPR',
 'WLF': 'WPR',
 'WSM': 'WPR',
 'YEM': 'EMR',
 'ZAF': 'AFR',
 'ZMB': 'AFR',
 'ZWE': 'AFR'
}

def get_continent(country):
    return country_to_continent.get(country, 'Unknown')